// <auto-generated />
namespace MVCProJect.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adddatatomembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddatatomembership));
        
        string IMigrationMetadata.Id
        {
            get { return "201903101834386_add data to membership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
